### ISSUE TITLE
pal_ifx_i2c_config.o No rule to make

### ISSUE THREAD

**Issue by jamborloi** [Infineon/personalize-optiga-trust-x#1]
Compiling optiga_trust_x/pal/linux/pal_os_event.c
Compiling optiga_trust_x/pal/linux/pal_os_lock.c
Compiling optiga_trust_x/pal/linux/pal_os_timer.c
make: *** No rule to make target 'build/./optiga_trust_x/pal/linux/target/rpi3/pal_ifx_i2c_config.o', needed by 'build/optiga_generate_csr'.  Stop.

pi@DRUMSv2:~/optiga/personalize-optiga-trust-x/source/build/optiga_trust_x/pal/linux $ ls
pal_gpio.o  pal_i2c.o  pal.o  pal_os_event.o  pal_os_lock.o  pal_os_timer.o

**Comment by ayushev** [comment]
Hi, please use this repository for the personalization https://github.com/Infineon/personalize-optiga-trust

It works on RPI as well

**Comment by jamborloi** [comment]
hi, thanks,
I will try this
I got the optiga trust E as well. Does this work with E?
I am new to this. I would like to check if you have any instruction for the following:
1. Can this security chips do encrypt my raspbian sd card root partition like the zymbit?
2. can optiga x or E secured my i2c devices to only connect to my raspberry pi with my own pub key?
